Termux:Modify the community repository file location
mirrorz-org/mirrorz-help pull request #103
Opened 2023-06-23 09:52 UTC by Spz2022

2023-06-23 09:52 UTC, Spz2022 commented
这是我第1次pr，有什么不对的地方，请多多指教

2023-06-23 10:06 UTC, Spz2022 commented
https://github.com/mirrorz-org/mirrorz-help/issues/102

2023-06-24 01:54 UTC, ZenithalHourlyRate requested changes
My IME is broken so sorry for using English.

Please check autocorrect CI.

2023-06-24 01:54 UTC, ZenithalHourlyRate commented on contents/termux.mdx
>  </CodeBlock>
Add an empty line here.

2023-06-24 01:54 UTC, ZenithalHourlyRate commented on contents/termux.mdx
> +如果启用了其他repo(x11,root)请同时修改这些
Empty line and bullet point to organize both x11 and root part

```
* 如果启用了其他repo(x11,root)请同时修改这些
  + 如果启用了x11-repo则修改
  + 如果启用了root-repo则修改
```

2023-06-24 01:54 UTC, ZenithalHourlyRate commented on contents/termux.mdx
> +如果启用了x11-repo则修改
Add empty line here

2023-06-24 01:54 UTC, ZenithalHourlyRate commented on contents/termux.mdx
> +deb {{http_protocol}}{{mirror}} }/apt/termux-x11 x11 main
```suggestion
deb {{http_protocol}}{{mirror}}/apt/termux-x11 x11 main 
```

2023-06-24 01:54 UTC, ZenithalHourlyRate commented on contents/termux.mdx
> +deb {{http_protocol}}{{mirror}} }/apt/termux-root root stable
```suggestion
deb {{http_protocol}}{{mirror}}/apt/termux-root root stable 
```

2023-06-24 01:54 UTC, ZenithalHourlyRate commented on contents/termux.mdx
> +</CodeBlock>
Empty line here

2023-06-24 01:54 UTC, ZenithalHourlyRate commented on contents/termux.mdx
> +如果启用了root-repo则修改
Empty line here

2023-06-25 08:49 UTC, ZenithalHourlyRate commented
Check CI.

2023-06-26 10:07 UTC, Spz2022 commented
看来我想的太简单了，实际上不是

2023-08-24 05:30 UTC, taoky commented on contents/termux.mdx
> +社区源 (如果已经启用)
```suggestion
社区源（如果已经启用）
```

2023-08-24 05:31 UTC, taoky commented on contents/termux.mdx
> +sed -i 's@^\(deb.*x11 main\)$@#\1\ndeb {{http_protocol}}{{mirror}}/apt/termux-x11 x11 main @' $PREFIX/etc/apt/sources.list.d/x11.list
与 `{{http_protocol}}` 相关的模板替换需要在 `<CodeBlock>` 中。

2023-08-24 05:33 UTC, taoky commented
> 看来我想的太简单了，实际上不是

@Spz2022 建议本地配置 node 环境后根据 README.md 中 `Get started` 部分实际运行测试再提交修改。

2023-08-31 12:35 UTC, taoky commented on contents/termux.mdx
> +```bash
需要在 `<CodeBlock>` 后和 `</CodeBlock>` 前加空格，保证与其他文档的格式统一。

2023-09-01 05:07 UTC, taoky submitted a review, later dismissed

2023-09-01 05:07 UTC, taoky commented
@Spz2022 CI 这个修了我就合并了。

2023-09-01 05:15 UTC, eastonman commented
我可以修一下

2023-09-01 05:20 UTC, taoky approved these changes

2023-09-01 05:20 UTC, merged