contents(debian*,ubuntu*): add DEB822 examples
mirrorz-org/mirrorz-help pull request #140
Opened 2024-04-24 12:56 UTC by taoky

2024-04-24 15:26 UTC, Harry-Chen reviewed
内容上没有问题。但感觉两层或者更多的注释看起来不是很优雅。

此外，有办法去掉不存在的 suite 吗？比如 `sid-{security,backports,updates}` 可能会引起困惑。

2024-04-24 16:03 UTC, TechCiel requested changes
`debian-security` 和 ubuntu 相关的结构比较简单还好，`debian` 的建议做一些改动：

1. 将 source repo 和对应的二进制 repo 紧邻安排，便于需要时查找
2. 考虑到只能使用注释关闭内容，建议明确各个开关标签的优先关系，避免 `{{enable_source}}{{is_sid}}` 和  `{{is_sid}}{{enable_source}}` 两种顺序同时出现

如果时间不足我明天上午可以帮忙改一下。

2024-04-24 16:05 UTC, TechCiel commented
> 有办法去掉不存在的 suite 吗？

AFAIK, 在当前的 mirrorz-help 架构里大概是无法隐藏一段内容的

2024-04-24 16:30 UTC, SukkaW commented on contents/debian-security.mdx
> +传统格式（`/etc/apt/sources.list`）：
<img width="668" alt="image" src="https://github.com/mirrorz-org/mirrorz-help/assets/40715044/f7c3d917-b644-4817-a82d-d281712824f5">

This doesn't look nice, let's add `##` here.

```suggestion
## 传统格式（`/etc/apt/sources.list`）：
```

2024-04-24 16:30 UTC, SukkaW commented on contents/debian-security.mdx
> +DEB822 格式（`/etc/apt/sources.list.d/debian.sources`）：
```suggestion
## DEB822 格式（`/etc/apt/sources.list.d/debian.sources`）：
```

2024-04-24 16:55 UTC, taoky commented on contents/debian-security.mdx
> +传统格式（`/etc/apt/sources.list`）：
测试了一下，需要四级标题，否则 toc 会生成失败。不过效果也还不错：

![image](https://github.com/mirrorz-org/mirrorz-help/assets/2109893/793ece3a-a347-47b8-ac94-3deccc00c833)

2024-04-24 17:50 UTC, TechCiel approved these changes
Suggestions made via Telegram are fixed.

LGTM now. I have no further concerns after checking preview build.

2024-04-27 15:41 UTC, Harry-Chen commented on contents/debian.mdx
> +{{enable_source}}Suites: {{release_name}}
既然 Ubuntu 的合并了，Debian 这边是否把 foo foo-updates foo-backports 都放在一起，再减少一些

2024-04-27 15:42 UTC, Harry-Chen commented on contents/debian.mdx
> +{{security_official}}{{is_sid}}Types: deb
是否在官方 / 非官方安全更新的上方都保留注释，供用户后续切换参考（不仅仅此处，包括所有）

2024-04-27 16:20 UTC, taoky commented on contents/debian.mdx
> +{{enable_source}}Suites: {{release_name}}
0370a2ebfb7cc3f520fb9139645919b663f9278a

2024-04-27 16:20 UTC, taoky commented on contents/debian.mdx
> +{{security_official}}{{is_sid}}Types: deb
好，要加的话 one-line-style 的也一起加了

2024-04-27 16:29 UTC, Harry-Chen commented on contents/debian.mdx
> +{{security_official}}{{is_sid}}Types: deb
是的，我就是这个意思

2024-04-27 16:31 UTC, taoky commented on contents/debian.mdx
> +{{security_official}}{{is_sid}}Types: deb
0f4b9f1b03dde5ffb64d45bfdd11d3a6138320a5，但是我感觉效果可能不太好（可能注释内容要改一下）

2024-04-27 16:55 UTC, Harry-Chen approved these changes
Looks good to me now.

2024-04-27 16:56 UTC, merged