同步 Ubuntu 生命周期
mirrorz-org/mirrorz-help pull request #142
Opened 2024-04-26 05:40 UTC by zjw2017

添加 Ubuntu 24.04 LTS 至 ubuntu 和 ubuntu-ports
调整 Ubuntu 22.04 LTS 的顺序
调整 Ubuntu 14.04 LTS 和 Ubuntu 23.04 至 ubuntu-old-releases

Ubuntu 24.04 LTS 于 2024 年 4 月 25 日 发布，生命周期 2034 年 4 月 Ubuntu 14.04 LTS 于 2014 年 4 月 17 日 发布，生命周期 2024 年 4 月
Ubuntu 23.04        于 2023 年 4 月 20 日 发布，生命周期 2024 年 1 月 25 日
数据来源：https://wiki.ubuntu.com/Releases/

2024-04-26 05:51 UTC, Harry-Chen requested changes
内容改动不恰当

2024-04-26 05:51 UTC, Harry-Chen commented on contents/ubuntu-old-releases.mdx
> +        ['14.04 LTS', { release_name: 'trusty' }],
这里的内容不是随意添加的。上游的版本只有这么多 ，添加额外版本只会让用户困惑

https://mirror.nju.edu.cn/ubuntu-old-releases/ubuntu/dists/

2024-04-26 05:51 UTC, Harry-Chen commented on contents/ubuntu-ports.mdx
> -        ['23.04', { release_name: 'lunar' }],
lunar 并没有从主源中移除。

2024-04-26 06:27 UTC, zjw2017 commented
> 内容改动不恰当

已还原部分修改

2024-04-26 06:58 UTC, taoky commented
我倾向于在 #140 合并之后再处理这个 PR。

2024-04-26 07:03 UTC, zjw2017 commented
> 我倾向于在 #140 合并之后再处理这个 PR。

没问题，按你们的计划进行

2024-04-27 16:59 UTC, taoky approved these changes

2024-04-27 16:59 UTC, Harry-Chen approved these changes
LGTM

2024-04-27 16:59 UTC, merged