Opensuse tumbleweed update
mirrorz-org/mirrorz-help pull request #148
Opened 2024-05-31 14:10 UTC by weearc

- Update `openSUSE` document:
  - remove some of descriptions of `tumbleweed update` repo
  - update document about RIS
  - update document of slowroll 
  - update document about adding repos manually in YaST2 
  - update document of repo prioity
- Update `packman` document:
  - update method of tumbleweed and slowroll
  - update description of vendor change and prioity in zypper command

2024-05-31 15:18 UTC, taoky requested changes

2024-05-31 15:18 UTC, taoky commented on contents/opensuse.mdx
> +如许还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
```suggestion
如需还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
```

2024-05-31 15:18 UTC, taoky commented on contents/opensuse.mdx
> +添加镜像源，并启用更高优先级用以覆盖官方镜像(可更改 `98` 为更小的数字，越小优先级越高）
```suggestion
添加镜像源，并启用更高优先级用以覆盖官方镜像（可更改 `98` 为更小的数字，越小优先级越高）
```

2024-05-31 15:18 UTC, taoky commented on contents/opensuse.mdx
> +本方法中提供了一种禁用 RIS 的方法来实现临时禁用 RIS 自动刷新。
所以，如果用户需要手动设置镜像，那么需要禁用 RIS 且「还原为传统镜像源管理方式」吗？这里的表述不太清楚。

2024-05-31 15:31 UTC, weearc commented on contents/opensuse.mdx
> +本方法中提供了一种禁用 RIS 的方法来实现临时禁用 RIS 自动刷新。
> 那么需要禁用 RIS 且「还原为传统镜像源管理方式」吗？这里的表述不太清楚。

不需要，但启用 RIS 会多出额外的需要刷新官方源的过程。镜像根据优先级高低排列，低优先级数字的优先采用，因此是否启用 RIS 和实际使用哪个镜像无关。但完全干掉 RIS 可以省略这个每次刷新时候，尽管不再使用官方源但仍然需要刷新的步骤。

不推荐关掉 RIS 是因为 openSUSE 官方不推荐这么做，以及需要锁包以防更新。不适合小白用户操作。

2024-05-31 15:42 UTC, weearc commented on contents/opensuse.mdx
> +本方法中提供了一种禁用 RIS 的方法来实现临时禁用 RIS 自动刷新。
在 [b5850fc](https://github.com/mirrorz-org/mirrorz-help/pull/148/commits/b5850fcb77f8156a59df52444764d3116dce9559) 进行了更改

2024-06-01 10:39 UTC, taoky requested changes

2024-06-01 10:39 UTC, taoky commented on contents/opensuse.mdx
> +    |Leap|OSS|{{http_protocol}}{{mirror}}/distribution/leap/$releasever/repo/oss/|-|
只有 `<CodeBlock>` 块里面才能用变量，所以这里的 `{{http_protocol}}{{mirror}}/` 可能不得不删掉。

2024-06-01 10:39 UTC, taoky commented on contents/packman.mdx
> +编辑后需要使用如下命令完成对应软件包的来源替换:
```suggestion
编辑后需要使用如下命令完成对应软件包的来源替换：
```

2024-06-01 10:39 UTC, taoky commented on contents/opensuse.mdx
> +由于 RIS 的存在，手工关闭单个官方源仓库的刷新，将在下次执行更新操作时被重新启用。仍需要和官方源（download.opensuse.org）进行同步，因此在不更改 `openSUSE` 服务的前提下，所有针对官方源的修改将在下次仓库或软件更新时被覆盖或重置。
[主语？]仍需要和官方源（download.opensuse.org）进行同步

2024-06-01 11:04 UTC, weearc commented on contents/opensuse.mdx
> +由于 RIS 的存在，手工关闭单个官方源仓库的刷新，将在下次执行更新操作时被重新启用。仍需要和官方源（download.opensuse.org）进行同步，因此在不更改 `openSUSE` 服务的前提下，所有针对官方源的修改将在下次仓库或软件更新时被覆盖或重置。
Fix in [d572d7d](https://github.com/mirrorz-org/mirrorz-help/pull/148/commits/d572d7da3af1acb65cf3b5d9fd75c193f899c718)

2024-06-01 17:50 UTC, taoky commented on contents/opensuse.mdx
> +sudo zypper remove openSUSE-repos-*
```suggestion
{{sudo}}zypper remove openSUSE-repos-*
```

2024-06-01 17:55 UTC, taoky commented on contents/opensuse.mdx
> +如需还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
所以是有三种方式：

- 保持默认使用 RIS，不需要额外配置
- 部分关闭（？）RIS
- 彻底关闭 RIS（传统镜像源管理方式？）

这个理解是正确的吗？

2024-06-01 18:05 UTC, weearc commented on contents/opensuse.mdx
> +如需还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
理解是正确的。

默认情况下，使用RIS无需额外配置。注册在  mirrorcache 的 mirrorz 中包含 opensuse 的镜像站在各自区域内默认就会被分流到。

部分禁用指以下两种中一种：
- 手动指定新的源+高优先级并禁用官方源=仍会定期刷新官方源缓存但使用被指定的镜像
- 手动通过配置文件关闭服务和自动刷新，但下次 RIS 相关包被更新时，修改将被覆盖，即被重新启用

传统方式指完全移除 RIS 相关包。用传统包管理方式来管理镜像源

2024-06-02 05:09 UTC, taoky commented on contents/opensuse.mdx
> +sudo zypper remove openSUSE-repos-*
还有两个 `sudo` 也要修改。

2024-06-02 05:11 UTC, taoky commented on contents/opensuse.mdx
> +如需还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
> 但下次 RIS 相关包被更新时，修改将被覆盖，即被重新启用

那听起来没有什么意义，帮助文档可以不包含这种方法？只提供两种选择：要么用更高优先级，要么关掉 RIS

2024-06-02 05:21 UTC, weearc commented on contents/opensuse.mdx
> +如需还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
> 那听起来没有什么意义，帮助文档可以不包含这种方法？只提供两种选择：要么用更高优先级，要么关掉 RIS

不推荐直接关掉的原因是比如当启用了 NVIDIA 仓库但禁用官方源 RIS 时候时候会：
![image](https://github.com/mirrorz-org/mirrorz-help/assets/19357165/2e1d3695-a458-47c5-82c5-f3c9a8c31d84)
如图，直接被同等干掉，因为 NV 是依赖 RIS 的。对于有系统管理经验的人来说可能就是加个锁的事，但是对于初级用户可能会因为随意移除导致下次更新时可能出现各种问题

2024-06-02 05:23 UTC, weearc commented on contents/opensuse.mdx
> +如需还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
官方现在主要在推 RIS ，我们不知道恢复传统镜像管理的方式在哪一个时间节点会失效，因此留下一个虽然麻烦，但是不需要额外维护系统的方法我认为仍然是必要的。选择交给用户。初级用户可能就会使用稍微麻烦但稳定的方法，高级用户更可能会按照自己的需求来使用。

2024-06-02 05:26 UTC, weearc commented on contents/opensuse.mdx
> +sudo zypper remove openSUSE-repos-*
done [4098ddc](https://github.com/mirrorz-org/mirrorz-help/pull/148/commits/4098ddc1b997fbe47ca1a9c4a4fc4e7e68252ca5)

2024-06-02 07:03 UTC, taoky commented on contents/opensuse.mdx
> +如需还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
可以用列表的方式列出来这几种选择吗？这样可以更清晰一些。

2024-06-02 07:04 UTC, weearc commented on contents/opensuse.mdx
> +如需还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
> 可以用列表的方式列出来这几种选择吗？这样可以更清晰一些。

这确实是个更可靠的做法。我去改一下

2024-06-02 07:41 UTC, weearc commented on contents/opensuse.mdx
> +如需还原为传统镜像源管理方式，确保在 `bash` 或 `zsh` 下执行：
[31b6300](https://github.com/mirrorz-org/mirrorz-help/pull/148/commits/31b63005ae2054358d162772641af1f8ad9b3afe)

2024-06-02 15:35 UTC, taoky commented on contents/opensuse.mdx
> +在此目标下，通常无需对系统软件源进行任何更改，更新时会被自动分流至任意**同时**[注册到 MirrorCache](https://mirrors.opensuse.org) 和校园网联合镜像的镜像站。这也是官方最推荐的做法。
> **同时**[注册到 MirrorCache](https://mirrors.opensuse.org) 和校园网联合镜像的镜像站

这个描述是只对选择 "mirrors.cernet.edu.cn" 的时候有效吗？帮助页面是可以选择具体某一个镜像的。

2024-06-02 15:57 UTC, weearc commented on contents/opensuse.mdx
> +在此目标下，通常无需对系统软件源进行任何更改，更新时会被自动分流至任意**同时**[注册到 MirrorCache](https://mirrors.opensuse.org) 和校园网联合镜像的镜像站。这也是官方最推荐的做法。
> 这个描述是只对选择 "mirrors.cernet.edu.cn" 的时候有效吗？帮助页面是可以选择具体某一个镜像的。

不是的，是指针对中国大陆服务时，需要满足首先注册到 mirrorcache ，其次在 mirrorz 注册，与是否选择 mirrors.cernet.edu.cn  无关。

2024-06-02 16:41 UTC, taoky commented on contents/opensuse.mdx
> +在此目标下，通常无需对系统软件源进行任何更改，更新时会被自动分流至任意**同时**[注册到 MirrorCache](https://mirrors.opensuse.org) 和校园网联合镜像的镜像站。这也是官方最推荐的做法。
> 不是的，是指针对中国大陆服务时，需要满足首先注册到 mirrorcache ，其次在 mirrorz 注册，与是否选择 mirrors.cernet.edu.cn 无关。

这是 OpenSUSE 一方的设置？

2024-06-03 05:36 UTC, weearc commented on contents/opensuse.mdx
> +在此目标下，通常无需对系统软件源进行任何更改，更新时会被自动分流至任意**同时**[注册到 MirrorCache](https://mirrors.opensuse.org) 和校园网联合镜像的镜像站。这也是官方最推荐的做法。
[a8f3a6d](https://github.com/mirrorz-org/mirrorz-help/pull/148/commits/a8f3a6d893fea45983ce3acf51b7bd63ee268f44)

2024-06-03 06:12 UTC, taoky approved these changes

2024-06-03 06:14 UTC, taoky commented
等一下，还有一个问题：

```
CodeBlock: If you don' use {{variable}} syntax in your code, and don't use "enableQuickSetup", you don't have to use <CodeBlock />. The extraneous <CodeBlock /> has code starts with: ls -la /etc/zypp/repos.d/*.rpmsave
```

建议本地跑一下，修掉两个文档出现的 warning。

2024-06-03 07:03 UTC, taoky approved these changes

2024-06-03 07:04 UTC, merged